### PR TITLE
Hard wrap existing docs, Tabbed blocks

### PR DESCRIPTION
**Pull request by CBroz1**
This PR...

1. Adds tabbed blocks to `mkdocs.yaml`
2. Adds a tab block to Mantra.md, providing an example of use
3. Hard wraps markdown files with the goal of making future git diffs easier to read. These single line breaks are not rendered in the output site, but make identifying changes much easier in PRs

No other changes have been made

### CODE REVIEW

**Review by guzman-raphael — CHANGES_REQUESTED** [review]
@CBroz1 :bulb: Great idea! :bulb: 

One thing this PR doesn't capture though is the logic to wrap lines. We might as well capture that so that we can all be consistent. This might be best done by saving the VSCode formatting options. Maybe we can use `prettier`? :shrug:

**Comment by CBroz1** [comment]
> Maybe we can use `prettier`? 🤷

I've been using [Rewrap](https://stkb.github.io/Rewrap/). Would it be easier for me to setup Prettier because some folks on the team already have it? Either way, I can figure out how to add a settings file

**Comment by CBroz1** [comment]
@guzman-raphael [This branch](https://github.com/CBroz1/datajoint-docs/tree/dev#linters-and-settings) describes my wrap/lint/spell-check approach. Lmk if you think this will work for the broader team.

**Review by kabilar — APPROVED** [review]

**Comment by kabilar** [comment]
Thanks team.  @guzman-raphael has handed off the docs to me this week, so I will merge this pull request.  We can add rewrap instructions in #18.

**Review by guzman-raphael — APPROVED** [review]

**Pull request merged**
